name: Detect and Process Changed Folders

on:
  schedule:
    # Runs every 15 minutes
    - cron: "*/15 * * * *"

jobs:
  process-changed-folders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Detect and Process Changed Folders
        run: |
          #!/bin/bash

          # Fetch the latest changes
          git fetch --prune --unshallow

          # Get the last commit hash in the timeframe (15-30 minutes ago)
          LAST_COMMIT=$(git log -n 1 --format="%H" --since="30 minutes ago" --until="15 minutes ago")
          if [ -z "$LAST_COMMIT" ]; then
            echo "No commits found in the specified timeframe (15-30 minutes ago)."
            exit 0
          fi

          # Extract changed files for the specified commit and filter for new folders under 'clients/'
          CHANGED_FOLDERS=$(git diff-tree --no-commit-id --name-only -r $LAST_COMMIT | grep -E '^clients/[^/]+/' | cut -d '/' -f 2 | sort -u)

          # Check if any folders were detected
          if [ -z "$CHANGED_FOLDERS" ]; then
            echo "No changed folders detected under 'clients/'."
            exit 0
          fi

          # Output the detected folders
          echo "Detected changed folders:"
          echo "$CHANGED_FOLDERS"

          # Run commands for each folder
          for folder in $CHANGED_FOLDERS; do
            echo "Running commands for folder: $folder"
            # Add your specific commands here
            cd "clients/$folder" || continue
            echo "Running custom commands in $folder"
            # Example: Run your commands, such as npm install, build, etc.
            # npm install
            # npm run build
            echo "Commands completed for $folder"
          done

          echo "Processing complete."
