name: Static Site Deployment

on:
  push:
    branches:
      - test
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout Test Branch with full history
      - name: Checkout Test Branch
        uses: actions/checkout@v4
        with:
          repository: ar7u4/gitcheckpr
          ref: test
          path: test-repo
          fetch-depth: 0  # Needed for git push

      # Checkout Main Branch
      - name: Checkout Main Branch
        uses: actions/checkout@v4
        with:
          repository: ar7u4/gitcheckpr
          ref: main
          path: main-repo

      # Copy files from main to test
      - name: Copy Files from Main to Test Repo
        run: cp -r main-repo/dashboard2 test-repo/dashboard2

      # Configure Git for test branch
      - name: Configure Git
        run: |
          cd test-repo
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      # Commit and push changes to test branch
      - name: Commit and Push to Test Branch
        run: |
          cd test-repo
          git add dashboard2/
          git commit -m "Sync dashboard2 from main branch" || echo "No changes to commit"
          git push origin test

      # Prepare combined deployment directory
      - name: Prepare Deployment Directory
        run: |
          mkdir -p deploy/test deploy/main
          cp -r test-repo/dashboard2/* deploy/test/
          cp -r main-repo/dashboard2/* deploy/main/

      # Upload combined artifact for Pages
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: deploy/

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      # Output Deployed URLs
      - name: Display Deployed URLs
        run: |
          echo "Test Branch Live at: ${{ steps.deployment.outputs.page_url }}/test/"
          echo "Main Branch Live at: ${{ steps.deployment.outputs.page_url }}/main/"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true