name: Daily Commit Changes

on:
        # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "main" ]
  schedule:
    - cron: "*/15 * * * *"  # Runs every day at midnight

    # Triggers the workflow on push or pull request events but only for the "main" branch

jobs:
  process-changes-today:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Timezone to IST
        run: sudo timedatectl set-timezone Asia/Kolkata

      - name: Fetch Latest Changes
        run: git fetch --prune --unshallow

      - name: Log the current time for comparison
        run: |
          CURRENT_TIME=$(date +"%Y-%m-%d %H:%M:%S")
          echo "Current pipeline run time: $CURRENT_TIME"

      - name: Get Changed Folders from 12:00 and 18:00 today
        run: |
          # Get commits from 00:00 to 15:00 today
          COMMITS=$(git log --since="today 17:15" --before="today 20:00" --format="%H")

          if [ -z "$COMMITS" ]; then
            echo "No commits found between 12:00 and 22:00 today."
            exit 0
          fi

          # Detect all changed folders across the commits
          echo "$COMMITS" | \
          xargs -I {} git diff-tree --no-commit-id --name-only -r {} | \
          grep '/' | awk -F'/' '{OFS="/"; $NF=""; print $0}' | sort -u > changed_folders.txt

          # Check if there are any changes
          if [ ! -s changed_folders.txt ]; then
            echo "No folders detected between 00:00 and 15:00 today."
            exit 0
          fi

          # Print the detected folders for logging
          echo "Changed folders from 12:00 and 18:00 today:"
          cat changed_folders.txt

      - name: Process Each Folder
        run: |
          # Process each folder detected in the last step
          while IFS= read -r folder; do
            echo "Processing folder: $folder"
            cd "$folder" || continue
            # Run your custom commands here
            ls -l
            cd - >/dev/null
          done < changed_folders.txt